In [1]:
import numpy as np

In [2]:
#Create numpy array  via 1D list
list1=[1,2,3,4,5,6]
arr1=np.array(list1)
print(arr1)
type(arr1)

[1 2 3 4 5 6]


numpy.ndarray

In [3]:
#create 2D array
list2=[[1,2,3],[5,4,6]]
arr2=np.array(list2,dtype='float32')
arr2


array([[1., 2., 3.],
       [5., 4., 6.]], dtype=float32)

In [4]:
#create numpy array via built in array creation functions
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.ones((2,3),dtype='float')

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [7]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
np.random.random((3,3))

array([[0.14841407, 0.86245049, 0.62619735],
       [0.22143887, 0.92642257, 0.69060527],
       [0.84828227, 0.25313612, 0.15861851]])

In [9]:
#mean=0 and Standard deviation=1
np.random.normal(0,1,(3,3))

array([[-0.29572001,  1.01195032, -0.39389685],
       [-1.02204517, -1.299187  ,  0.34270508],
       [-0.75340659,  0.06597297, -1.84578784]])

In [10]:
#interval(0,10)
np.random.randint(0,10,(3,3))

array([[2, 4, 4],
       [4, 9, 1],
       [7, 3, 7]])

In [11]:
sample_array=np.array([
    [1,2,3],[4,5,6],[7,8,9]
])

In [12]:
print(f"The dimension of sample array is :{sample_array.ndim}")

The dimension of sample array is :2


In [13]:
sample_array2=np.array([[[1,2,3],[2,3,5],[2,5,6]]])
print(f"The dimension of sample array is :{sample_array2.ndim}")

The dimension of sample array is :3


In [14]:
print(f"The shape of sample array is :{sample_array.shape}")
print(f"The datatype of sample array is :{sample_array.dtype}")
print(f"The size of each element of sample array is :{sample_array.size}")

The shape of sample array is :(3, 3)
The datatype of sample array is :int64
The size of each element of sample array is :9


In [15]:
#Create numpy array  via 1D list
list1=[1,'Santosh',2]
arr1=np.array(list1)
print(arr1)
type(arr1)

['1' 'Santosh' '2']


numpy.ndarray

In [16]:
# Define a nested list to represent the array
array_without_numpy = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# Display the array
for row in array_without_numpy:
    print(row)


[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [17]:
a=np.array([0,1,2,3,4])
print(f'1st item:{a[0]}')
print(f'2nd item:{a[1]}')
print(f'3rd item:{a[2]}')
print(f'4th item:{a[3]}')
print(f'5th item:{a[4]}')

1st item:0
2nd item:1
3rd item:2
4th item:3
5th item:4


In [18]:
arr_idx_2d=np.array([
    [11,12,13],
    [21,22,23],
    [31,32,33]
])
print(arr_idx_2d[0,0])
print(arr_idx_2d[0,1])
print(arr_idx_2d[0,2])
print(arr_idx_2d[1,0])
print(arr_idx_2d[1,1])
print(arr_idx_2d[1,2])
print(arr_idx_2d[2,0])
print(arr_idx_2d[2,1])
print(arr_idx_2d[2,2])

11
12
13
21
22
23
31
32
33


In [19]:
#slice 1D array
arr1=np.array([1,2,3,4,5,6,7])
arr1_slice=arr1[1:5]
print(arr1_slice)

[2 3 4 5]


In [20]:
arr1[4:] # return all elements after 4 

array([5, 6, 7])

In [21]:
arr1[::2]  #return every element fom numpy array exclude 2

array([1, 3, 5, 7])

In [22]:
arr1[-3:-1] 

array([5, 6])

In [23]:
arr1[::-1] #reverse right to left

array([7, 6, 5, 4, 3, 2, 1])

In [24]:
#slice 2D array
arr2=np.array([
    [11,12,13],
    [21,22,33],
    [31,32,33]
])
arr2[1,1:]

array([22, 33])

In [25]:
base_arr=np.array([1,2,3,4,5,6])
print(base_arr)

[1 2 3 4 5 6]


In [26]:
#copy arr
copy_arr=base_arr.copy()
print(copy_arr)

[1 2 3 4 5 6]


In [27]:
copy_arr=base_arr.copy() #
# copy_arr=base_arr #same memory address share or not
print(copy_arr)

[1 2 3 4 5 6]


In [28]:
print(f'''Do original array and copy array shares an memory ?
      Ans:{np.shares_memory(base_arr,copy_arr)}''')

Do original array and copy array shares an memory ?
      Ans:False


In [29]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
np.reshape(arr,(4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
arr.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [31]:
arr5=np.array([1,2,3,4,5,6,7,8])
np.reshape(arr5,(3,3))

ValueError: cannot reshape array of size 8 into shape (3,3)

In [ ]:
#concatenate 1d array
arr1=np.array([1,1,1,1])
arr2=np.array([2,2,2,2])
concat_arr=np.concatenate((arr1,arr2))
concat_arr

array([1, 1, 1, 1, 2, 2, 2, 2])

In [ ]:
#concatenate 2d array
a=np.array([
    [1,1,1],
    [1,1,1]
])

b=np.array([
    [9,9,9],
    [9,9,9]
])
c=np.concatenate((a,b))
c

array([[1, 1, 1],
       [1, 1, 1],
       [9, 9, 9],
       [9, 9, 9]])

In [ ]:
#concatenate 2d array (axis=1)
concat1=np.concatenate((a,b),axis=1)
concat1

array([[1, 1, 1, 9, 9, 9],
       [1, 1, 1, 9, 9, 9]])

In [ ]:
#splitting 1D array i.e [1,2,3,4,5,6] into 4 parts
array=[1,2,3,4,5,6]
np.array_split(array,4)


[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [ ]:
split_array_2d=np.array([
[1,2,3],
[4,5,6],
[7,8,9],
[10,11,12],
[13,14,15],
[16,17,18]
])
np.array_split(split_array_2d,4,axis=1)



[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]]),
 array([], shape=(6, 0), dtype=int64)]

In [ ]:
import time
x1=np.arange(1,1000000)
x2=np.arange(1,1000000)
mul=np.zeros(x1.shape)
start_time=time.process_time()

for i in range(len(x1)):
    mul[i]=x1[i]* x2[i]

end_time=time.process_time()
print(end_time - start_time)

1.6195654070000005


In [ ]:
#broadcasting with scalars
a=np.array([1,2,3])
b=2

print(a+b)

[3 4 5]


In [ ]:
#broadcasting with 1d and 2d arrays
a=np.array([1,2,3])
b=np.array([[10],[20],[30]])

print(a+b)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
#broadcasting with incompatible shapes
