In [2]:
import numpy as np

In [3]:
#Create numpy array  via 1D list
list1=[1,2,3,4,5,6]
arr1=np.array(list1)
print(arr1)
type(arr1)

[1 2 3 4 5 6]


numpy.ndarray

In [4]:
#create 2D array
list2=[[1,2,3],[5,4,6]]
arr2=np.array(list2,dtype='float32')
arr2


array([[1., 2., 3.],
       [5., 4., 6.]], dtype=float32)

In [5]:
#create numpy array via built in array creation functions
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.ones((2,3),dtype='float')

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [8]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.random.random((3,3))

array([[0.04696799, 0.25348993, 0.40636784],
       [0.49369171, 0.86266866, 0.95622164],
       [0.18995732, 0.0367899 , 0.28925026]])

In [10]:
#mean=0 and Standard deviation=1
np.random.normal(0,1,(3,3))

array([[-0.25596174,  0.74007315,  0.42316734],
       [ 0.30254591,  1.57137175, -0.30768234],
       [-0.71665854, -1.42132409,  1.21570886]])

In [11]:
#interval(0,10)
np.random.randint(0,10,(3,3))

array([[9, 9, 4],
       [7, 6, 7],
       [5, 1, 8]])

In [12]:
sample_array=np.array([
    [1,2,3],[4,5,6],[7,8,9]
])

In [13]:
print(f"The dimension of sample array is :{sample_array.ndim}")

The dimension of sample array is :2


In [14]:
sample_array2=np.array([[[1,2,3],[2,3,5],[2,5,6]]])
print(f"The dimension of sample array is :{sample_array2.ndim}")

The dimension of sample array is :3


In [15]:
print(f"The shape of sample array is :{sample_array.shape}")
print(f"The datatype of sample array is :{sample_array.dtype}")
print(f"The size of each element of sample array is :{sample_array.size}")

The shape of sample array is :(3, 3)
The datatype of sample array is :int64
The size of each element of sample array is :9


In [16]:
#Create numpy array  via 1D list
list1=[1,'Santosh',2]
arr1=np.array(list1)
print(arr1)
type(arr1)

['1' 'Santosh' '2']


numpy.ndarray

In [17]:
# Define a nested list to represent the array
array_without_numpy = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# Display the array
for row in array_without_numpy:
    print(row)


[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [19]:
a=np.array([0,1,2,3,4])
print(f'1st item:{a[0]}')
print(f'2nd item:{a[1]}')
print(f'3rd item:{a[2]}')
print(f'4th item:{a[3]}')
print(f'5th item:{a[4]}')

1st item:0
2nd item:1
3rd item:2
4th item:3
5th item:4


In [25]:
arr_idx_2d=np.array([
    [11,12,13],
    [21,22,23],
    [31,32,33]
])
print(arr_idx_2d[0,0])
print(arr_idx_2d[0,1])
print(arr_idx_2d[0,2])
print(arr_idx_2d[1,0])
print(arr_idx_2d[1,1])
print(arr_idx_2d[1,2])
print(arr_idx_2d[2,0])
print(arr_idx_2d[2,1])
print(arr_idx_2d[2,2])

11
12
13
21
22
23
31
32
33


In [27]:
#slice 1D array
arr1=np.array([1,2,3,4,5,6,7])
arr1_slice=arr1[1:5]
print(arr1_slice)

[2 3 4 5]


In [28]:
arr1[4:] # return all elements after 4 

array([5, 6, 7])

In [29]:
arr1[::2]  #return every element fom numpy array exclude 2

array([1, 3, 5, 7])

In [30]:
arr1[-3:-1] 

array([5, 6])

In [31]:
arr1[::-1] #reverse right to left

array([7, 6, 5, 4, 3, 2, 1])

In [34]:
#slice 2D array
arr2=np.array([
    [11,12,13],
    [21,22,33],
    [31,32,33]
])
arr2[1,1:]

array([22, 33])

In [35]:
base_arr=np.array([1,2,3,4,5,6])
print(base_arr)

[1 2 3 4 5 6]


In [37]:
#copy arr
copy_arr=base_arr.copy()
print(copy_arr)

[1 2 3 4 5 6]


In [43]:
copy_arr=base_arr.copy() #
# copy_arr=base_arr #same memory address share or not
print(copy_arr)

[1 2 3 4 5 6]


In [44]:
print(f'''Do original array and copy array shares an memory ?
      Ans:{np.shares_memory(base_arr,copy_arr)}''')

Do original array and copy array shares an memory ?
      Ans:False
