In [1]:
import numpy as np

In [5]:
#Create numpy array  via 1D list
list1=[1,2,3,4,5,6]
arr1=np.array(list1)
print(arr1)
type(arr1)

[1 2 3 4 5 6]


numpy.ndarray

In [10]:
#create 2D array
list2=[[1,2,3],[5,4,6]]
arr2=np.array(list2,dtype='float32')
arr2


array([[1., 2., 3.],
       [5., 4., 6.]], dtype=float32)

In [15]:
#create numpy array via built in array creation functions
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.ones((2,3),dtype='float')

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [18]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
np.random.random((3,3))

array([[0.97133484, 0.42129983, 0.88469112],
       [0.00168159, 0.45707192, 0.80989983],
       [0.28488892, 0.35667234, 0.52330218]])

In [26]:
#mean=0 and Standard deviation=1
np.random.normal(0,1,(3,3))

array([[-0.99815726, -1.04762543, -0.09284784],
       [-1.31226756, -0.03739675, -0.76999705],
       [ 0.83646004, -0.06472891, -1.02246485]])

In [32]:
#interval(0,10)
np.random.randint(0,10,(3,3))

array([[8, 8, 0],
       [9, 9, 5],
       [1, 6, 8]])

In [33]:
sample_array=np.array([
    [1,2,3],[4,5,6],[7,8,9]
])

In [34]:
print(f"The dimension of sample array is :{sample_array.ndim}")

The dimension of sample array is :2


In [42]:
sample_array2=np.array([[[1,2,3],[2,3,5],[2,5,6]]])
print(f"The dimension of sample array is :{sample_array2.ndim}")

The dimension of sample array is :3


In [48]:
print(f"The shape of sample array is :{sample_array.shape}")
print(f"The datatype of sample array is :{sample_array.dtype}")
print(f"The size of each element of sample array is :{sample_array.size}")

The shape of sample array is :(3, 3)
The datatype of sample array is :int64
The size of each element of sample array is :9


In [51]:
#Create numpy array  via 1D list
list1=[1,'Santosh',2]
arr1=np.array(list1)
print(arr1)
type(arr1)

['1' 'Santosh' '2']


numpy.ndarray